-- Add quicksoap_count column to track QuickSOAP generation usage
-- This allows tracking QuickSOAP usage similar to quick_query_count for PetQuery

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS quicksoap_count integer DEFAULT 0;

-- Add index for performance when aggregating usage metrics
CREATE INDEX IF NOT EXISTS idx_users_quicksoap_count ON public.users(quicksoap_count);

-- Add comment for documentation
COMMENT ON COLUMN public.users.quicksoap_count IS 
  'Total number of QuickSOAP reports generated by this user (cumulative count)';
