import React, { useEffect } from 'react';
import '../styles/Legal.css';
import Footer from './Footer';

const Terms = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
        document.body.scrollTop = 0;    // For Safari
        document.documentElement.scrollTop = 0;  // For Chrome, Firefox, IE and Opera
    }, []);

    return (
        <>
            <div className="legal-container">


                <div className="legal-content">
                    <section>
                        <h2>Terms of Service</h2>
                        <p><strong>Effective Date:</strong> January 1, 2025</p>
                        <p>
                            These Terms and Conditions govern the use of the PetWise service and website
                            (collectively referred to as "the Service"). By using the Service, you agree to be
                            bound by these Terms and Conditions.
                        </p>

                        <h3>1. Acceptance of Terms</h3>
                        <p>
                            By accessing or using PetWise, you acknowledge that you have read, understood, and
                            agree to be bound by these Terms and Conditions, including any additional terms,
                            conditions, or policies incorporated by reference.
                        </p>
                        <p>
                            Users must expressly acknowledge critical disclaimers, including limitations of
                            liability and the informational nature of AI-generated content, during onboarding.
                            Continued use of the Service constitutes acceptance of these Terms.
                        </p>

                        <h3>2. Service Description</h3>
                        <p>
                            PetWise is an AI-powered application designed to assist veterinary professionals in
                            generating detailed veterinary prognosis records ("Record Generator") and providing
                            quick medical suggestions ("QuickMed Query"). The Service enables users to input
                            patient information (such as species, breed, weight, clinical findings) and receive
                            AI-generated records or suggestions based on the provided data.
                        </p>
                        <p>
                            PetWise explicitly states that the Service is not a substitute for professional
                            veterinary judgment or advice.
                        </p>

                        <h3>3. User Responsibilities</h3>

                        <h4>Accurate Information</h4>
                        <p>
                            Users must provide accurate and complete information when using the Service. PetWise
                            is not responsible for any inaccuracies in the information provided by the user.
                        </p>

                        <h4>Verification by Licensed Veterinarian</h4>
                        <p>
                            All veterinary records generated by the Record Generator and all outputs from the
                            QuickMed Query are intended for informational purposes only and must be reviewed and
                            verified by a licensed veterinarian. PetWise does not provide veterinary advice or
                            medical opinions and disclaims any liability for decisions made based on AI-generated
                            content.
                        </p>

                        <h4>Assumption of Risk</h4>
                        <p>
                            Users acknowledge and accept that AI-generated records or suggestions from the
                            Record Generator and QuickMed Query may contain errors, omissions, or inaccuracies
                            and assume all risks associated with their use. Users waive any claims against
                            PetWise arising from reliance on AI-generated content.
                        </p>

                        <h4>Treatment Responsibility</h4>
                        <p>
                            PetWise is not responsible for any treatments, diagnoses, or medical procedures
                            performed based on the information provided by the Record Generator or QuickMed Query.
                            Licensed veterinarians are solely responsible for all decisions and actions taken
                            based on these outputs.
                        </p>

                        <h4>Inputting and Storing Data</h4>
                        <p>
                            Users are solely responsible for the content they input, generate, or save using the
                            Service. The platform is not intended for storing sensitive or personally
                            identifiable information ("PII") about clients, including but not limited to names,
                            addresses, phone numbers, and email addresses.
                        </p>
                        <ul>
                            <li>Users agree not to input, store, or save any PII in records or other fields.</li>
                            <li>
                                Any PII entered or saved by users is done at their own risk, and users agree to
                                comply with applicable privacy laws and regulations.
                            </li>
                            <li>
                                PetWise reserves the right to delete or anonymize data suspected of containing PII.
                            </li>
                            <li>
                                PetWise does not monitor, review, or verify the content input or stored by users.
                                Users are solely responsible for ensuring compliance with applicable laws regarding
                                the data they input.
                            </li>
                        </ul>

                        <h4>Consent for Third-Party Data</h4>
                        <p>
                            Users must obtain all necessary consents from individuals whose data is input into
                            the Service. PetWise disclaims all liability for data input without proper
                            authorization or consent.
                        </p>

                        <h4>Indemnification</h4>
                        <p>
                            Users agree to defend, indemnify, and hold PetWise harmless from any claims, damages,
                            or liabilities arising from their use of the Service, including but not limited to:
                        </p>
                        <ul>
                            <li>Misuse of the platform, Record Generator, or QuickMed Query.</li>
                            <li>Input, storage, or sharing of unauthorized or sensitive data.</li>
                            <li>
                                Claims from third parties related to reliance on outputs from the Record Generator
                                or QuickMed Query.
                            </li>
                        </ul>

                        <h3>4. Subscription and Payment</h3>
                        <h4>Free Trial</h4>
                        <p>PetWise offers a 14-day free trial for new users.</p>

                        <h4>Subscription Fees</h4>
                        <p>Subscriptions are charged on a monthly or yearly basis, as selected by the user.</p>

                        <h4>Refunds</h4>
                        <p>
                            Refunds for subscription payments are only available under exceptional circumstances,
                            such as incorrect billing or technical issues that prevent access to the Service. If
                            you believe you are entitled to a refund, please contact our support team within 30
                            days of the charge.
                        </p>

                        <h4>No Refund for Record Generation or Queries</h4>
                        <p>
                            Since PetWise provides digital content, all charges for record generation or QuickMed
                            Query usage are non-refundable. Users are encouraged to thoroughly review the Service
                            during their free trial.
                        </p>

                        <h3>5. Data Protection and Privacy</h3>
                        <h4>Personal Information</h4>
                        <p>
                            When signing up, PetWise collects personal information such as your name, email
                            address, and payment details through Auth0 and Stripe.
                        </p>

                        <h4>Veterinary Records and Queries</h4>
                        <p>
                            Users may input and store patient-related data (species, breed, diagnosis, etc.) for
                            generating records or queries. The Service is not designed to store client data
                            (e.g., client names, phone numbers, addresses), and users are advised not to include
                            such information in stored records or query inputs.
                        </p>

                        <h3>6. Limitation of Liability</h3>
                        <p>To the fullest extent permitted by law:</p>
                        <ul>
                            <li>
                                PetWise is not liable for any direct, indirect, incidental, special, or
                                consequential damages arising from the use of the Service, including the Record
                                Generator or QuickMed Query.
                            </li>
                            <li>
                                PetWise is not responsible for the misuse of the platform, Record Generator, or
                                QuickMed Query by users.
                            </li>
                            <li>
                                PetWise disclaims all liability for errors, omissions, or decisions made based on
                                AI-generated content from the Record Generator or QuickMed Query.
                            </li>
                            <li>
                                Users waive all claims against PetWise related to the content or usage of
                                AI-generated records or suggestions.
                            </li>
                        </ul>

                        <h3>7. Governing Law and Dispute Resolution</h3>
                        <p>
                            These Terms are governed by the laws of the jurisdiction in which PetWise operates.
                            Any disputes arising from the use of the Service will be resolved through binding
                            arbitration, with users waiving their right to participate in class action lawsuits.
                        </p>

                        <h3>8. Modifications to Terms</h3>
                        <p>
                            PetWise reserves the right to update these Terms and Conditions at any time. Changes
                            will be effective upon posting on the Service. Continued use of the Service
                            constitutes acceptance of the updated Terms.
                        </p>

                        <h3>9. Contact Information</h3>
                        <p>For any questions or concerns, please contact us at: support@petwise.vet</p>


                    </section>
                </div>
            </div>
            <Footer />
        </>
    );
};

export default Terms; 